spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test2
    username: root
    password: ssafy

  profiles:
    group:
      "local": "local, common"
      "development": "development, common"
    active: local

  config:
    activate:
      on-profile: "common"
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: yeonybucket
    stack:
      auto: false


  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000 #최적화 옵션

logging.level:
  org.hibernate.SQL: debug

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

---
# 로컬 환경
spring:
  environment: "local"
  config:
    activate:
      on-profile: "local"
  file-dir: /src/main/resources/static/files/
---
# 배포 환경
spring:
  environment: "development"
  config:
    activate:
      on-profile: "development"
  file-dir: /home/ubuntu/fileupload/