spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test2
    username: root
    password: ssafy
---
spring:
  profiles:
    group:
      "local": "local, common"
      "development": "development, common"
    active: local
---
spring:
  config:
    activate:
      on-profile: "common"
  servlet:
    multipart:
      max-file-size: 5GB
      max-request-size: 5GB

  jwt:
    key: move248_secret_key_slakflkajlskjdflkjalksjdlfkjasjdlkfjlasjdlfjalsjfjasdfkjl
    live:
#      atk: 1800000 #30분
      atk: 30000
      rtk: 7200000 #2시간

  redis:
    host: localhost
    port: 6379
#    password: your-redis-server-password (설정하지 않았다면 생략)

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000 #최적화 옵션

logging.level:
  org.hibernate.SQL: debug

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: yeonybucket
    stack:
      auto: false
    credentials:
      instance-profile: true
      access-key: ENC(ygiolVWr3vioSlXjufEa0N3yy14Motmb7E9tZ3ZlEFk=)
      secret-key: ENC(3MsOma3EhOtToXCgljBugcQru5SqMgUbB3ESnjx6PEVt/WtqCvzJzB88MJmQd7ex+Ns6M6ghrSA=)

---
# 로컬 환경
spring:
  environment: "local"
  config:
    activate:
      on-profile: "local"
  file-dir: /src/main/resources/static/files/
---
# 배포 환경
spring:
  environment: "development"
  config:
    activate:
      on-profile: "development"
  file-dir: /home/ubuntu/fileupload/
---
jasypt:
  encryptor:
    password: ${ENCODE_KEY}